### ISSUE TITLE
JNose Test vs. Test Smell Detector

### ISSUE THREAD

**Issue by jose** [arieslab/jnose#44]
Hi,

Quick question, is JNose Test based on [Test Smell Detector](https://github.com/TestSmells/TestSmellDetector) or is it the other way around?  [JNose Test's source code](https://github.com/arieslab/jnose/tree/main/src/main/java/br/ufba/jnose/base/testsmelldetector) is so similar to [Test Smell Detector's source code](https://github.com/TestSmells/TestSmellDetector/tree/master/src/main/java) that I'm wondering which one is based on which one.

--
Best,
Jose

**Comment by tassiovirginio** [comment]
JNose is based on the Test Smells Detector code.

**Comment by jose** [comment]
Ok, thanks.

**Comment by tassiovirginio** [comment]
JNose's idea was to facilitate the collection of data about test smells, and we ended up working on the detection part of the production classes, test classes, on the display of the detected test smells code, among other features.

I am available to answer any questions.
